# Generated by Django 5.1.7 on 2025-05-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome_perfil', models.CharField(max_length=255)),
                ('rg_perfil', models.CharField(max_length=255)),
                ('nascimento_perfil', models.DateTimeField(max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('foto_pet', models.ImageField(blank=True, null=True, upload_to='')),
                ('matricula_pet', models.CharField(max_length=255)),
                ('nome_pet', models.CharField(max_length=200)),
                ('nascimento_pet', models.DateTimeField()),
                ('id_perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='meupetApp.perfil')),
            ],
        ),
    ]
