# Generated by Django 5.1.7 on 2025-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('matricula_pet', models.CharField(max_length=255)),
                ('nome_pet', models.CharField(max_length=200)),
                ('nascimento_pet', models.DateTimeField()),
            ],
        ),
    ]
